### ISSUE TITLE
docs: document PathConstraints and HeaderConstraints properties properly

### ISSUE THREAD

**Issue by dhalperi** [batfish/pybatfish#690]
If I look at the docs for [`bfq.reachability`](https://pybatfish.readthedocs.io/en/latest/notebooks/forwarding.html#Reachability), the `DispositionSpec` link goes to a page explaining the specifier.

However, the `HeaderConstraints` link goes to python documentation instead of a custom documentation page. Same for `Path`. This makes it pretty hard on our users (Rick Donato on Slack, this time)

**Comment by ratulm** [comment]
What is the ideal here? Header and Path constraints are classes in Python,
so the documentation takes them there (as it does for Flow, Trace, etc.)
DispositionSpec is a string from Python perspective.

Dan - Are you imagining that we create custom pages for Header and Path
constraints, instead of, say, enhancing the python documentation of those
classes?

**Comment by dhalperi** [comment]
Header and Path Constraints have specs in them. Users should be able to get to those spec documentations.
